version: 2

sources:
  - name: jaffle_shop
    database: dbt-training-445820   # Update this with the correct database name
    schema: dbt_ll                  
    tables:
      - name: customers
      - name: orders
