version: 2

sources:
  - name: jaffle_shop  # Logical source name
    database: dbt-training-445820  # BigQuery project ID
    schema: dbt_ll  # BigQuery dataset name
    tables:
      - name: jaffle_customers
      - name: jaffle_orders
