version: 2

sources:
  - name: stripe  # This should match the 'stripe' source in your model
    database: dbt-training-445820  # BigQuery project ID
    schema: dbt_ll  # BigQuery dataset name
    tables:
      - name: stripe_payments  # This should match exactly with your source reference
